:: set WORKSPACE to point to the Common libraries main directory.

:: Export the standard set of environment variables.  
::
:: This script uses ${COMMON_WORKSPACE} if it is set.  It will use ${WORKSPACE} if ${COMMON_WORKSPACE} is not set
:: If neither is set, it will set both to the current directory
if NOT DEFINED TARGET_CONFIG (
   SET TARGET_CONFIG=Win32
)
SET TARGET_NAME=WinHost
@echo TARGET_NAME=%TARGET_NAME%

IF NOT DEFINED WORKSPACE (
   SET WORKSPACE=%~dp0..\..
)

IF NOT DEFINED COMMON_WORKSPACE (
   SET COMMON_WORKSPACE=%WORKSPACE%
)
echo Setting Common libraries environment variables
echo COMMON_WORKSPACE is %COMMON_WORKSPACE%

:: Set our build variables.
SET COMMON_SCRIPT_HOME=%COMMON_WORKSPACE%\CommandScripts\WinTools
SET COMMON_SRC_HOME=%COMMON_WORKSPACE%\source
SET COMMON_PRODUCT_HOME=%COMMON_SRC_HOME%\Product
SET COMMON_TEST_HOME=%COMMON_SRC_HOME%\Tests
SET COMMON_THIRDPARTY_HOME=%COMMON_SRC_HOME%\ThirdParty

SET COMMON_OUTPUT_PREFIX=%COMMON_WORKSPACE%\output_%TARGET_NAME%\%TARGET_CONFIG%
SET COMMON_RELEASE_OUT_HOME=%COMMON_OUTPUT_PREFIX%\Release
SET COMMON_RELEASEWITHDEB_OUT_HOME=%COMMON_OUTPUT_PREFIX%\RelWithDebInfo
SET COMMON_DEBUG_OUT_HOME=%COMMON_OUTPUT_PREFIX%\Debug
SET COMMON_TEST_OUT_HOME=%COMMON_OUTPUT_PREFIX%\Test

SET COMMON_MAIN_CMAKE_DIR=%COMMON_WORKSPACE%
SET COMMON_BUILD_DIR=%COMMON_MAIN_CMAKE_DIR%\build_%TARGET_NAME%\%TARGET_CONFIG%

SET COMMON_THIRDPARTY_LIB_PATH_DEBUG=%COMMON_THIRDPARTY_HOME%\lib\%TARGET_NAME%\%TARGET_CONFIG%\Debug
SET COMMON_THIRDPARTY_LIB_PATH_RELEASE=%COMMON_THIRDPARTY_HOME%\lib\%TARGET_NAME%\%TARGET_CONFIG%\Release
