:: set WORKSPACE to point to the Common libraries main directory.

:: Export the standard set of environment variables.  
::
:: This script uses ${COMMON_WORKSPACE} if it is set.  It will use ${WORKSPACE} if ${COMMON_WORKSPACE} is not set
:: If neither is set, it will set both to the current directory

IF NOT DEFINED WORKSPACE (
   SET WORKSPACE=%~dp0..\..
)

IF NOT DEFINED COMMON_WORKSPACE (
   SET COMMON_WORKSPACE=%WORKSPACE%
)
echo Setting Common libraries environment variables
echo COMMON_WORKSPACE is %COMMON_WORKSPACE%

:: Set our build variables.
SET TARGET_NAME=WinHost
SET COMMON_SCRIPT_HOME=%COMMON_WORKSPACE%\CommandScripts\WinTools
SET COMMON_SRC_HOME=%COMMON_WORKSPACE%\source
SET COMMON_PRODUCT_HOME=%COMMON_SRC_HOME%\Product
SET COMMON_TEST_HOME=%COMMON_SRC_HOME%\Tests
SET COMMON_THIRDPARTY_HOME=%COMMON_SRC_HOME%\ThirdParty

SET COMMON_OUTPUT_PATH=%COMMON_WORKSPACE%
SET COMMON_OUTPUT_PREFIX=%COMMON_OUTPUT_PATH%\Output%
SET COMMON_RELEASE_OUT_HOME=%COMMON_OUTPUT_PREFIX%Release\%TARGET_NAME%
SET COMMON_RELEASEWITHDEB_OUT_HOME=%COMMON_OUTPUT_PREFIX%RelWithDebInfo\%TARGET_NAME%
SET COMMON_DEBUG_OUT_HOME=%COMMON_OUTPUT_PREFIX%Debug\%TARGET_NAME%
SET COMMON_TEST_OUT_HOME=%COMMON_OUTPUT_PREFIX%Test\%TARGET_NAME%

SET COMMON_MAIN_CMAKE_DIR=%COMMON_WORKSPACE%
SET COMMON_BUILD_DIR=%COMMON_MAIN_CMAKE_DIR%\build_%TARGET_NAME%

SET COMMON_THIRDPARTY_LIB_PATH_DEBUG=%COMMON_THIRDPARTY_HOME%\lib\%TARGET_NAME%\Debug
SET COMMON_THIRDPARTY_LIB_PATH_RELEASE=%COMMON_THIRDPARTY_HOME%\lib\%TARGET_NAME%\Release
