// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CommonMessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Matrix.MsgService.CommonMessages {

  /// <summary>Holder for reflection information generated from CommonMessages.proto</summary>
  public static partial class CommonMessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for CommonMessages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonMessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDb21tb25NZXNzYWdlcy5wcm90bxIgTWF0cml4Lk1zZ1NlcnZpY2UuQ29t",
            "bW9uTWVzc2FnZXMiiAIKBkhlYWRlchI8Cgltc2dUeXBlSUQYASABKA4yKS5N",
            "YXRyaXguTXNnU2VydmljZS5Db21tb25NZXNzYWdlcy5Nc2dUeXBlEg4KBm1z",
            "Z0tleRgCIAEoBRIWCg5vcmlnQ2xpZW50VHlwZRgDIAEoBRIUCgxvcmlnQ2xp",
            "ZW50SUQYBCABKAUSFgoOZGVzdENsaWVudFR5cGUYBSABKAUSFAoMZGVzdENs",
            "aWVudElEGAYgASgFEg8KB2Fja0tleXMYByADKAUSDQoFdG9waWMYCCABKAUS",
            "EgoKaXNBcmNoaXZlZBgJIAEoCBITCgtyZXBseU1zZ0tleRgKIAEoBRILCgNt",
            "c2cYDyABKAwiLgoLTmFja0RldGFpbHMSDgoGcmVhc29uGAEgASgFEg8KB2Rl",
            "dGFpbHMYAiABKAkiLQoFTG9nb24SEgoKY2xpZW50VHlwZRgBIAEoBRIQCghj",
            "bGllbnRJRBgCIAEoBSJACglTdWJzY3JpYmUSEgoKY2xpZW50VHlwZRgBIAEo",
            "BRIQCghjbGllbnRJRBgCIAEoBRINCgV0b3BpYxgDIAEoBSp1CgdNc2dUeXBl",
            "EhQKEElOVkFMSURfTVNHX1RZUEUQABIHCgNBQ0sQARIJCgVMT0dPThACEgoK",
            "BkxPR09GRhADEg0KCVNVQlNDUklCRRAEEg8KC1VOU1VCU0NSSUJFEAUSCAoE",
            "TkFDSxAGEgoKBkNVU1RPTRBkQgJIA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Matrix.MsgService.CommonMessages.MsgType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Matrix.MsgService.CommonMessages.Header), global::Matrix.MsgService.CommonMessages.Header.Parser, new[]{ "MsgTypeID", "MsgKey", "OrigClientType", "OrigClientID", "DestClientType", "DestClientID", "AckKeys", "Topic", "IsArchived", "ReplyMsgKey", "Msg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Matrix.MsgService.CommonMessages.NackDetails), global::Matrix.MsgService.CommonMessages.NackDetails.Parser, new[]{ "Reason", "Details" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Matrix.MsgService.CommonMessages.Logon), global::Matrix.MsgService.CommonMessages.Logon.Parser, new[]{ "ClientType", "ClientID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Matrix.MsgService.CommonMessages.Subscribe), global::Matrix.MsgService.CommonMessages.Subscribe.Parser, new[]{ "ClientType", "ClientID", "Topic" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Value stored in the MsgTypeID field - determines the type of message it is.
  ///* It is used to interpret a Header to parse it into the proper structure.
  ///* In general, the name of the message type can be translated to the ProtoCmd name
  ///*     by converting to Pascal case and removing the underscore
  ///*     e.g. DOOR_STATUS_REQ is the MsgType for the DoorStatusReq message
  ///* Some messages may handle multiple MsgTypeIDs
  /// </summary>
  public enum MsgType {
    [pbr::OriginalName("INVALID_MSG_TYPE")] InvalidMsgType = 0,
    [pbr::OriginalName("ACK")] Ack = 1,
    [pbr::OriginalName("LOGON")] Logon = 2,
    [pbr::OriginalName("LOGOFF")] Logoff = 3,
    [pbr::OriginalName("SUBSCRIBE")] Subscribe = 4,
    [pbr::OriginalName("UNSUBSCRIBE")] Unsubscribe = 5,
    [pbr::OriginalName("NACK")] Nack = 6,
    [pbr::OriginalName("CUSTOM")] Custom = 100,
  }

  #endregion

  #region Messages
  /// <summary>
  ///For now, this message is here to help interpret all the other messages.
  ///In future we may want to always send two messages but for ease of programming, 
  ///we are just including the two fields in each message.
  ///msgKey is an integer sequence that is used to marry a reply message to a request message
  /// </summary>
  public sealed partial class Header : pb::IMessage<Header> {
    private static readonly pb::MessageParser<Header> _parser = new pb::MessageParser<Header>(() => new Header());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Header> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Matrix.MsgService.CommonMessages.CommonMessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Header() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Header(Header other) : this() {
      msgTypeID_ = other.msgTypeID_;
      msgKey_ = other.msgKey_;
      origClientType_ = other.origClientType_;
      origClientID_ = other.origClientID_;
      destClientType_ = other.destClientType_;
      destClientID_ = other.destClientID_;
      ackKeys_ = other.ackKeys_.Clone();
      topic_ = other.topic_;
      isArchived_ = other.isArchived_;
      replyMsgKey_ = other.replyMsgKey_;
      msg_ = other.msg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Header Clone() {
      return new Header(this);
    }

    /// <summary>Field number for the "msgTypeID" field.</summary>
    public const int MsgTypeIDFieldNumber = 1;
    private global::Matrix.MsgService.CommonMessages.MsgType msgTypeID_ = global::Matrix.MsgService.CommonMessages.MsgType.InvalidMsgType;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Matrix.MsgService.CommonMessages.MsgType MsgTypeID {
      get { return msgTypeID_; }
      set {
        msgTypeID_ = value;
      }
    }

    /// <summary>Field number for the "msgKey" field.</summary>
    public const int MsgKeyFieldNumber = 2;
    private int msgKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MsgKey {
      get { return msgKey_; }
      set {
        msgKey_ = value;
      }
    }

    /// <summary>Field number for the "origClientType" field.</summary>
    public const int OrigClientTypeFieldNumber = 3;
    private int origClientType_;
    /// <summary>
    ///the client type of the originating client
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int OrigClientType {
      get { return origClientType_; }
      set {
        origClientType_ = value;
      }
    }

    /// <summary>Field number for the "origClientID" field.</summary>
    public const int OrigClientIDFieldNumber = 4;
    private int origClientID_;
    /// <summary>
    ///the client ID of the originating client
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int OrigClientID {
      get { return origClientID_; }
      set {
        origClientID_ = value;
      }
    }

    /// <summary>Field number for the "destClientType" field.</summary>
    public const int DestClientTypeFieldNumber = 5;
    private int destClientType_;
    /// <summary>
    ///the client type of the destination client if message is intended for a specific client
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DestClientType {
      get { return destClientType_; }
      set {
        destClientType_ = value;
      }
    }

    /// <summary>Field number for the "destClientID" field.</summary>
    public const int DestClientIDFieldNumber = 6;
    private int destClientID_;
    /// <summary>
    ///the client type of the destination client if message is intended for a specific client
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DestClientID {
      get { return destClientID_; }
      set {
        destClientID_ = value;
      }
    }

    /// <summary>Field number for the "ackKeys" field.</summary>
    public const int AckKeysFieldNumber = 7;
    private static readonly pb::FieldCodec<int> _repeated_ackKeys_codec
        = pb::FieldCodec.ForInt32(58);
    private readonly pbc::RepeatedField<int> ackKeys_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///keys that this message is acking (does not have to be an ACK message)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> AckKeys {
      get { return ackKeys_; }
    }

    /// <summary>Field number for the "topic" field.</summary>
    public const int TopicFieldNumber = 8;
    private int topic_;
    /// <summary>
    ///topic of this message (for subscription purposes)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Topic {
      get { return topic_; }
      set {
        topic_ = value;
      }
    }

    /// <summary>Field number for the "isArchived" field.</summary>
    public const int IsArchivedFieldNumber = 9;
    private bool isArchived_;
    /// <summary>
    ///true if the sender was offline when it occurred
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsArchived {
      get { return isArchived_; }
      set {
        isArchived_ = value;
      }
    }

    /// <summary>Field number for the "replyMsgKey" field.</summary>
    public const int ReplyMsgKeyFieldNumber = 10;
    private int replyMsgKey_;
    /// <summary>
    ///if non zero, this message is a reply to a message sent with msgKey equal to replyMsgKey
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ReplyMsgKey {
      get { return replyMsgKey_; }
      set {
        replyMsgKey_ = value;
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 15;
    private pb::ByteString msg_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Header);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Header other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgTypeID != other.MsgTypeID) return false;
      if (MsgKey != other.MsgKey) return false;
      if (OrigClientType != other.OrigClientType) return false;
      if (OrigClientID != other.OrigClientID) return false;
      if (DestClientType != other.DestClientType) return false;
      if (DestClientID != other.DestClientID) return false;
      if(!ackKeys_.Equals(other.ackKeys_)) return false;
      if (Topic != other.Topic) return false;
      if (IsArchived != other.IsArchived) return false;
      if (ReplyMsgKey != other.ReplyMsgKey) return false;
      if (Msg != other.Msg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgTypeID != global::Matrix.MsgService.CommonMessages.MsgType.InvalidMsgType) hash ^= MsgTypeID.GetHashCode();
      if (MsgKey != 0) hash ^= MsgKey.GetHashCode();
      if (OrigClientType != 0) hash ^= OrigClientType.GetHashCode();
      if (OrigClientID != 0) hash ^= OrigClientID.GetHashCode();
      if (DestClientType != 0) hash ^= DestClientType.GetHashCode();
      if (DestClientID != 0) hash ^= DestClientID.GetHashCode();
      hash ^= ackKeys_.GetHashCode();
      if (Topic != 0) hash ^= Topic.GetHashCode();
      if (IsArchived != false) hash ^= IsArchived.GetHashCode();
      if (ReplyMsgKey != 0) hash ^= ReplyMsgKey.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MsgTypeID != global::Matrix.MsgService.CommonMessages.MsgType.InvalidMsgType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgTypeID);
      }
      if (MsgKey != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MsgKey);
      }
      if (OrigClientType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(OrigClientType);
      }
      if (OrigClientID != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(OrigClientID);
      }
      if (DestClientType != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(DestClientType);
      }
      if (DestClientID != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(DestClientID);
      }
      ackKeys_.WriteTo(output, _repeated_ackKeys_codec);
      if (Topic != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Topic);
      }
      if (IsArchived != false) {
        output.WriteRawTag(72);
        output.WriteBool(IsArchived);
      }
      if (ReplyMsgKey != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(ReplyMsgKey);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(122);
        output.WriteBytes(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MsgTypeID != global::Matrix.MsgService.CommonMessages.MsgType.InvalidMsgType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgTypeID);
      }
      if (MsgKey != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MsgKey);
      }
      if (OrigClientType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OrigClientType);
      }
      if (OrigClientID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OrigClientID);
      }
      if (DestClientType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DestClientType);
      }
      if (DestClientID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DestClientID);
      }
      size += ackKeys_.CalculateSize(_repeated_ackKeys_codec);
      if (Topic != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Topic);
      }
      if (IsArchived != false) {
        size += 1 + 1;
      }
      if (ReplyMsgKey != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReplyMsgKey);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Msg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Header other) {
      if (other == null) {
        return;
      }
      if (other.MsgTypeID != global::Matrix.MsgService.CommonMessages.MsgType.InvalidMsgType) {
        MsgTypeID = other.MsgTypeID;
      }
      if (other.MsgKey != 0) {
        MsgKey = other.MsgKey;
      }
      if (other.OrigClientType != 0) {
        OrigClientType = other.OrigClientType;
      }
      if (other.OrigClientID != 0) {
        OrigClientID = other.OrigClientID;
      }
      if (other.DestClientType != 0) {
        DestClientType = other.DestClientType;
      }
      if (other.DestClientID != 0) {
        DestClientID = other.DestClientID;
      }
      ackKeys_.Add(other.ackKeys_);
      if (other.Topic != 0) {
        Topic = other.Topic;
      }
      if (other.IsArchived != false) {
        IsArchived = other.IsArchived;
      }
      if (other.ReplyMsgKey != 0) {
        ReplyMsgKey = other.ReplyMsgKey;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MsgTypeID = (global::Matrix.MsgService.CommonMessages.MsgType) input.ReadEnum();
            break;
          }
          case 16: {
            MsgKey = input.ReadInt32();
            break;
          }
          case 24: {
            OrigClientType = input.ReadInt32();
            break;
          }
          case 32: {
            OrigClientID = input.ReadInt32();
            break;
          }
          case 40: {
            DestClientType = input.ReadInt32();
            break;
          }
          case 48: {
            DestClientID = input.ReadInt32();
            break;
          }
          case 58:
          case 56: {
            ackKeys_.AddEntriesFrom(input, _repeated_ackKeys_codec);
            break;
          }
          case 64: {
            Topic = input.ReadInt32();
            break;
          }
          case 72: {
            IsArchived = input.ReadBool();
            break;
          }
          case 80: {
            ReplyMsgKey = input.ReadInt32();
            break;
          }
          case 122: {
            Msg = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///message for NACK MsgType
  /// </summary>
  public sealed partial class NackDetails : pb::IMessage<NackDetails> {
    private static readonly pb::MessageParser<NackDetails> _parser = new pb::MessageParser<NackDetails>(() => new NackDetails());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NackDetails> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Matrix.MsgService.CommonMessages.CommonMessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NackDetails() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NackDetails(NackDetails other) : this() {
      reason_ = other.reason_;
      details_ = other.details_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NackDetails Clone() {
      return new NackDetails(this);
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 1;
    private int reason_;
    /// <summary>
    ///client/msgtype specific reason for the nack
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Reason {
      get { return reason_; }
      set {
        reason_ = value;
      }
    }

    /// <summary>Field number for the "details" field.</summary>
    public const int DetailsFieldNumber = 2;
    private string details_ = "";
    /// <summary>
    ///additional details
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Details {
      get { return details_; }
      set {
        details_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NackDetails);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NackDetails other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Reason != other.Reason) return false;
      if (Details != other.Details) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Reason != 0) hash ^= Reason.GetHashCode();
      if (Details.Length != 0) hash ^= Details.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Reason != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Reason);
      }
      if (Details.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Details);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Reason != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Reason);
      }
      if (Details.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Details);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NackDetails other) {
      if (other == null) {
        return;
      }
      if (other.Reason != 0) {
        Reason = other.Reason;
      }
      if (other.Details.Length != 0) {
        Details = other.Details;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Reason = input.ReadInt32();
            break;
          }
          case 18: {
            Details = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///message for LOGON MsgType
  /// </summary>
  public sealed partial class Logon : pb::IMessage<Logon> {
    private static readonly pb::MessageParser<Logon> _parser = new pb::MessageParser<Logon>(() => new Logon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Logon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Matrix.MsgService.CommonMessages.CommonMessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Logon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Logon(Logon other) : this() {
      clientType_ = other.clientType_;
      clientID_ = other.clientID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Logon Clone() {
      return new Logon(this);
    }

    /// <summary>Field number for the "clientType" field.</summary>
    public const int ClientTypeFieldNumber = 1;
    private int clientType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ClientType {
      get { return clientType_; }
      set {
        clientType_ = value;
      }
    }

    /// <summary>Field number for the "clientID" field.</summary>
    public const int ClientIDFieldNumber = 2;
    private int clientID_;
    /// <summary>
    ///unique id for client
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ClientID {
      get { return clientID_; }
      set {
        clientID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Logon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Logon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientType != other.ClientType) return false;
      if (ClientID != other.ClientID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientType != 0) hash ^= ClientType.GetHashCode();
      if (ClientID != 0) hash ^= ClientID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ClientType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ClientType);
      }
      if (ClientID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ClientID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ClientType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientType);
      }
      if (ClientID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Logon other) {
      if (other == null) {
        return;
      }
      if (other.ClientType != 0) {
        ClientType = other.ClientType;
      }
      if (other.ClientID != 0) {
        ClientID = other.ClientID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ClientType = input.ReadInt32();
            break;
          }
          case 16: {
            ClientID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///message for SUBSCRIBE/UNSUBSCRIBE MsgTypes
  /// </summary>
  public sealed partial class Subscribe : pb::IMessage<Subscribe> {
    private static readonly pb::MessageParser<Subscribe> _parser = new pb::MessageParser<Subscribe>(() => new Subscribe());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Subscribe> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Matrix.MsgService.CommonMessages.CommonMessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Subscribe() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Subscribe(Subscribe other) : this() {
      clientType_ = other.clientType_;
      clientID_ = other.clientID_;
      topic_ = other.topic_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Subscribe Clone() {
      return new Subscribe(this);
    }

    /// <summary>Field number for the "clientType" field.</summary>
    public const int ClientTypeFieldNumber = 1;
    private int clientType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ClientType {
      get { return clientType_; }
      set {
        clientType_ = value;
      }
    }

    /// <summary>Field number for the "clientID" field.</summary>
    public const int ClientIDFieldNumber = 2;
    private int clientID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ClientID {
      get { return clientID_; }
      set {
        clientID_ = value;
      }
    }

    /// <summary>Field number for the "topic" field.</summary>
    public const int TopicFieldNumber = 3;
    private int topic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Topic {
      get { return topic_; }
      set {
        topic_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Subscribe);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Subscribe other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientType != other.ClientType) return false;
      if (ClientID != other.ClientID) return false;
      if (Topic != other.Topic) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientType != 0) hash ^= ClientType.GetHashCode();
      if (ClientID != 0) hash ^= ClientID.GetHashCode();
      if (Topic != 0) hash ^= Topic.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ClientType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ClientType);
      }
      if (ClientID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ClientID);
      }
      if (Topic != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Topic);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ClientType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientType);
      }
      if (ClientID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientID);
      }
      if (Topic != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Topic);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Subscribe other) {
      if (other == null) {
        return;
      }
      if (other.ClientType != 0) {
        ClientType = other.ClientType;
      }
      if (other.ClientID != 0) {
        ClientID = other.ClientID;
      }
      if (other.Topic != 0) {
        Topic = other.Topic;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ClientType = input.ReadInt32();
            break;
          }
          case 16: {
            ClientID = input.ReadInt32();
            break;
          }
          case 24: {
            Topic = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
