#include "stdafx.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMessages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_CommonMessages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_CommonMessages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_CommonMessages_2eproto COMMONMESSAGES_API
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct COMMONMESSAGES_API TableStruct_CommonMessages_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace Matrix {
namespace MsgService {
namespace CommonMessages {
class Header;
class HeaderDefaultTypeInternal;
COMMONMESSAGES_API extern HeaderDefaultTypeInternal _Header_default_instance_;
class Logon;
class LogonDefaultTypeInternal;
COMMONMESSAGES_API extern LogonDefaultTypeInternal _Logon_default_instance_;
class NackDetails;
class NackDetailsDefaultTypeInternal;
COMMONMESSAGES_API extern NackDetailsDefaultTypeInternal _NackDetails_default_instance_;
class Subscribe;
class SubscribeDefaultTypeInternal;
COMMONMESSAGES_API extern SubscribeDefaultTypeInternal _Subscribe_default_instance_;
}  // namespace CommonMessages
}  // namespace MsgService
}  // namespace Matrix
PROTOBUF_NAMESPACE_OPEN
template<> COMMONMESSAGES_API ::Matrix::MsgService::CommonMessages::Header* Arena::CreateMaybeMessage<::Matrix::MsgService::CommonMessages::Header>(Arena*);
template<> COMMONMESSAGES_API ::Matrix::MsgService::CommonMessages::Logon* Arena::CreateMaybeMessage<::Matrix::MsgService::CommonMessages::Logon>(Arena*);
template<> COMMONMESSAGES_API ::Matrix::MsgService::CommonMessages::NackDetails* Arena::CreateMaybeMessage<::Matrix::MsgService::CommonMessages::NackDetails>(Arena*);
template<> COMMONMESSAGES_API ::Matrix::MsgService::CommonMessages::Subscribe* Arena::CreateMaybeMessage<::Matrix::MsgService::CommonMessages::Subscribe>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Matrix {
namespace MsgService {
namespace CommonMessages {

enum MsgType : int {
  INVALID_MSG_TYPE = 0,
  ACK = 1,
  LOGON = 2,
  LOGOFF = 3,
  SUBSCRIBE = 4,
  UNSUBSCRIBE = 5,
  NACK = 6,
  CUSTOM = 100,
  MsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  MsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
COMMONMESSAGES_API bool MsgType_IsValid(int value);
constexpr MsgType MsgType_MIN = INVALID_MSG_TYPE;
constexpr MsgType MsgType_MAX = CUSTOM;
constexpr int MsgType_ARRAYSIZE = MsgType_MAX + 1;

const std::string& MsgType_Name(MsgType value);
template<typename T>
inline const std::string& MsgType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MsgType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MsgType_Name.");
  return MsgType_Name(static_cast<MsgType>(enum_t_value));
}
bool MsgType_Parse(
    const std::string& name, MsgType* value);
// ===================================================================

class COMMONMESSAGES_API Header :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:Matrix.MsgService.CommonMessages.Header) */ {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);
  Header(Header&& from) noexcept
    : Header() {
    *this = ::std::move(from);
  }

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }
  inline Header& operator=(Header&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Header& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Header* internal_default_instance() {
    return reinterpret_cast<const Header*>(
               &_Header_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Header& a, Header& b) {
    a.Swap(&b);
  }
  inline void Swap(Header* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Header* New() const final {
    return CreateMaybeMessage<Header>(nullptr);
  }

  Header* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Header>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Header* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Matrix.MsgService.CommonMessages.Header";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAckKeysFieldNumber = 7,
    kMsgFieldNumber = 15,
    kMsgTypeIDFieldNumber = 1,
    kMsgKeyFieldNumber = 2,
    kOrigClientTypeFieldNumber = 3,
    kOrigClientIDFieldNumber = 4,
    kDestClientTypeFieldNumber = 5,
    kDestClientIDFieldNumber = 6,
    kTopicFieldNumber = 8,
    kIsArchivedFieldNumber = 9,
    kReplyMsgKeyFieldNumber = 10,
  };
  // repeated int32 ackKeys = 7;
  int ackkeys_size() const;
  private:
  int _internal_ackkeys_size() const;
  public:
  void clear_ackkeys();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_ackkeys(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_ackkeys() const;
  void _internal_add_ackkeys(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_ackkeys();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 ackkeys(int index) const;
  void set_ackkeys(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_ackkeys(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      ackkeys() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_ackkeys();

  // bytes msg = 15;
  void clear_msg();
  const std::string& msg() const;
  void set_msg(const std::string& value);
  void set_msg(std::string&& value);
  void set_msg(const char* value);
  void set_msg(const void* value, size_t size);
  std::string* mutable_msg();
  std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // .Matrix.MsgService.CommonMessages.MsgType msgTypeID = 1;
  void clear_msgtypeid();
  ::Matrix::MsgService::CommonMessages::MsgType msgtypeid() const;
  void set_msgtypeid(::Matrix::MsgService::CommonMessages::MsgType value);
  private:
  ::Matrix::MsgService::CommonMessages::MsgType _internal_msgtypeid() const;
  void _internal_set_msgtypeid(::Matrix::MsgService::CommonMessages::MsgType value);
  public:

  // int32 msgKey = 2;
  void clear_msgkey();
  ::PROTOBUF_NAMESPACE_ID::int32 msgkey() const;
  void set_msgkey(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_msgkey() const;
  void _internal_set_msgkey(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 origClientType = 3;
  void clear_origclienttype();
  ::PROTOBUF_NAMESPACE_ID::int32 origclienttype() const;
  void set_origclienttype(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_origclienttype() const;
  void _internal_set_origclienttype(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 origClientID = 4;
  void clear_origclientid();
  ::PROTOBUF_NAMESPACE_ID::int32 origclientid() const;
  void set_origclientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_origclientid() const;
  void _internal_set_origclientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 destClientType = 5;
  void clear_destclienttype();
  ::PROTOBUF_NAMESPACE_ID::int32 destclienttype() const;
  void set_destclienttype(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_destclienttype() const;
  void _internal_set_destclienttype(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 destClientID = 6;
  void clear_destclientid();
  ::PROTOBUF_NAMESPACE_ID::int32 destclientid() const;
  void set_destclientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_destclientid() const;
  void _internal_set_destclientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 topic = 8;
  void clear_topic();
  ::PROTOBUF_NAMESPACE_ID::int32 topic() const;
  void set_topic(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_topic() const;
  void _internal_set_topic(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // bool isArchived = 9;
  void clear_isarchived();
  bool isarchived() const;
  void set_isarchived(bool value);
  private:
  bool _internal_isarchived() const;
  void _internal_set_isarchived(bool value);
  public:

  // int32 replyMsgKey = 10;
  void clear_replymsgkey();
  ::PROTOBUF_NAMESPACE_ID::int32 replymsgkey() const;
  void set_replymsgkey(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_replymsgkey() const;
  void _internal_set_replymsgkey(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Matrix.MsgService.CommonMessages.Header)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > ackkeys_;
  mutable std::atomic<int> _ackkeys_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  int msgtypeid_;
  ::PROTOBUF_NAMESPACE_ID::int32 msgkey_;
  ::PROTOBUF_NAMESPACE_ID::int32 origclienttype_;
  ::PROTOBUF_NAMESPACE_ID::int32 origclientid_;
  ::PROTOBUF_NAMESPACE_ID::int32 destclienttype_;
  ::PROTOBUF_NAMESPACE_ID::int32 destclientid_;
  ::PROTOBUF_NAMESPACE_ID::int32 topic_;
  bool isarchived_;
  ::PROTOBUF_NAMESPACE_ID::int32 replymsgkey_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CommonMessages_2eproto;
};
// -------------------------------------------------------------------

class COMMONMESSAGES_API NackDetails :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:Matrix.MsgService.CommonMessages.NackDetails) */ {
 public:
  NackDetails();
  virtual ~NackDetails();

  NackDetails(const NackDetails& from);
  NackDetails(NackDetails&& from) noexcept
    : NackDetails() {
    *this = ::std::move(from);
  }

  inline NackDetails& operator=(const NackDetails& from) {
    CopyFrom(from);
    return *this;
  }
  inline NackDetails& operator=(NackDetails&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const NackDetails& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NackDetails* internal_default_instance() {
    return reinterpret_cast<const NackDetails*>(
               &_NackDetails_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(NackDetails& a, NackDetails& b) {
    a.Swap(&b);
  }
  inline void Swap(NackDetails* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NackDetails* New() const final {
    return CreateMaybeMessage<NackDetails>(nullptr);
  }

  NackDetails* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NackDetails>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const NackDetails& from);
  void MergeFrom(const NackDetails& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(NackDetails* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Matrix.MsgService.CommonMessages.NackDetails";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDetailsFieldNumber = 2,
    kReasonFieldNumber = 1,
  };
  // string details = 2;
  void clear_details();
  const std::string& details() const;
  void set_details(const std::string& value);
  void set_details(std::string&& value);
  void set_details(const char* value);
  void set_details(const char* value, size_t size);
  std::string* mutable_details();
  std::string* release_details();
  void set_allocated_details(std::string* details);
  private:
  const std::string& _internal_details() const;
  void _internal_set_details(const std::string& value);
  std::string* _internal_mutable_details();
  public:

  // int32 reason = 1;
  void clear_reason();
  ::PROTOBUF_NAMESPACE_ID::int32 reason() const;
  void set_reason(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_reason() const;
  void _internal_set_reason(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Matrix.MsgService.CommonMessages.NackDetails)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr details_;
  ::PROTOBUF_NAMESPACE_ID::int32 reason_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CommonMessages_2eproto;
};
// -------------------------------------------------------------------

class COMMONMESSAGES_API Logon :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:Matrix.MsgService.CommonMessages.Logon) */ {
 public:
  Logon();
  virtual ~Logon();

  Logon(const Logon& from);
  Logon(Logon&& from) noexcept
    : Logon() {
    *this = ::std::move(from);
  }

  inline Logon& operator=(const Logon& from) {
    CopyFrom(from);
    return *this;
  }
  inline Logon& operator=(Logon&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Logon& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Logon* internal_default_instance() {
    return reinterpret_cast<const Logon*>(
               &_Logon_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Logon& a, Logon& b) {
    a.Swap(&b);
  }
  inline void Swap(Logon* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Logon* New() const final {
    return CreateMaybeMessage<Logon>(nullptr);
  }

  Logon* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Logon>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const Logon& from);
  void MergeFrom(const Logon& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Logon* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Matrix.MsgService.CommonMessages.Logon";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientTypeFieldNumber = 1,
    kClientIDFieldNumber = 2,
  };
  // int32 clientType = 1;
  void clear_clienttype();
  ::PROTOBUF_NAMESPACE_ID::int32 clienttype() const;
  void set_clienttype(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_clienttype() const;
  void _internal_set_clienttype(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 clientID = 2;
  void clear_clientid();
  ::PROTOBUF_NAMESPACE_ID::int32 clientid() const;
  void set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_clientid() const;
  void _internal_set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Matrix.MsgService.CommonMessages.Logon)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 clienttype_;
  ::PROTOBUF_NAMESPACE_ID::int32 clientid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CommonMessages_2eproto;
};
// -------------------------------------------------------------------

class COMMONMESSAGES_API Subscribe :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:Matrix.MsgService.CommonMessages.Subscribe) */ {
 public:
  Subscribe();
  virtual ~Subscribe();

  Subscribe(const Subscribe& from);
  Subscribe(Subscribe&& from) noexcept
    : Subscribe() {
    *this = ::std::move(from);
  }

  inline Subscribe& operator=(const Subscribe& from) {
    CopyFrom(from);
    return *this;
  }
  inline Subscribe& operator=(Subscribe&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Subscribe& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Subscribe* internal_default_instance() {
    return reinterpret_cast<const Subscribe*>(
               &_Subscribe_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Subscribe& a, Subscribe& b) {
    a.Swap(&b);
  }
  inline void Swap(Subscribe* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Subscribe* New() const final {
    return CreateMaybeMessage<Subscribe>(nullptr);
  }

  Subscribe* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Subscribe>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const Subscribe& from);
  void MergeFrom(const Subscribe& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Subscribe* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Matrix.MsgService.CommonMessages.Subscribe";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientTypeFieldNumber = 1,
    kClientIDFieldNumber = 2,
    kTopicFieldNumber = 3,
  };
  // int32 clientType = 1;
  void clear_clienttype();
  ::PROTOBUF_NAMESPACE_ID::int32 clienttype() const;
  void set_clienttype(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_clienttype() const;
  void _internal_set_clienttype(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 clientID = 2;
  void clear_clientid();
  ::PROTOBUF_NAMESPACE_ID::int32 clientid() const;
  void set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_clientid() const;
  void _internal_set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 topic = 3;
  void clear_topic();
  ::PROTOBUF_NAMESPACE_ID::int32 topic() const;
  void set_topic(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_topic() const;
  void _internal_set_topic(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Matrix.MsgService.CommonMessages.Subscribe)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 clienttype_;
  ::PROTOBUF_NAMESPACE_ID::int32 clientid_;
  ::PROTOBUF_NAMESPACE_ID::int32 topic_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CommonMessages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Header

// .Matrix.MsgService.CommonMessages.MsgType msgTypeID = 1;
inline void Header::clear_msgtypeid() {
  msgtypeid_ = 0;
}
inline ::Matrix::MsgService::CommonMessages::MsgType Header::_internal_msgtypeid() const {
  return static_cast< ::Matrix::MsgService::CommonMessages::MsgType >(msgtypeid_);
}
inline ::Matrix::MsgService::CommonMessages::MsgType Header::msgtypeid() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.msgTypeID)
  return _internal_msgtypeid();
}
inline void Header::_internal_set_msgtypeid(::Matrix::MsgService::CommonMessages::MsgType value) {
  
  msgtypeid_ = value;
}
inline void Header::set_msgtypeid(::Matrix::MsgService::CommonMessages::MsgType value) {
  _internal_set_msgtypeid(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.msgTypeID)
}

// int32 msgKey = 2;
inline void Header::clear_msgkey() {
  msgkey_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::_internal_msgkey() const {
  return msgkey_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::msgkey() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.msgKey)
  return _internal_msgkey();
}
inline void Header::_internal_set_msgkey(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  msgkey_ = value;
}
inline void Header::set_msgkey(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_msgkey(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.msgKey)
}

// int32 origClientType = 3;
inline void Header::clear_origclienttype() {
  origclienttype_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::_internal_origclienttype() const {
  return origclienttype_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::origclienttype() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.origClientType)
  return _internal_origclienttype();
}
inline void Header::_internal_set_origclienttype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  origclienttype_ = value;
}
inline void Header::set_origclienttype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_origclienttype(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.origClientType)
}

// int32 origClientID = 4;
inline void Header::clear_origclientid() {
  origclientid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::_internal_origclientid() const {
  return origclientid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::origclientid() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.origClientID)
  return _internal_origclientid();
}
inline void Header::_internal_set_origclientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  origclientid_ = value;
}
inline void Header::set_origclientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_origclientid(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.origClientID)
}

// int32 destClientType = 5;
inline void Header::clear_destclienttype() {
  destclienttype_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::_internal_destclienttype() const {
  return destclienttype_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::destclienttype() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.destClientType)
  return _internal_destclienttype();
}
inline void Header::_internal_set_destclienttype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  destclienttype_ = value;
}
inline void Header::set_destclienttype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_destclienttype(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.destClientType)
}

// int32 destClientID = 6;
inline void Header::clear_destclientid() {
  destclientid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::_internal_destclientid() const {
  return destclientid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::destclientid() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.destClientID)
  return _internal_destclientid();
}
inline void Header::_internal_set_destclientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  destclientid_ = value;
}
inline void Header::set_destclientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_destclientid(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.destClientID)
}

// repeated int32 ackKeys = 7;
inline int Header::_internal_ackkeys_size() const {
  return ackkeys_.size();
}
inline int Header::ackkeys_size() const {
  return _internal_ackkeys_size();
}
inline void Header::clear_ackkeys() {
  ackkeys_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::_internal_ackkeys(int index) const {
  return ackkeys_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::ackkeys(int index) const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.ackKeys)
  return _internal_ackkeys(index);
}
inline void Header::set_ackkeys(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  ackkeys_.Set(index, value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.ackKeys)
}
inline void Header::_internal_add_ackkeys(::PROTOBUF_NAMESPACE_ID::int32 value) {
  ackkeys_.Add(value);
}
inline void Header::add_ackkeys(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_ackkeys(value);
  // @@protoc_insertion_point(field_add:Matrix.MsgService.CommonMessages.Header.ackKeys)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
Header::_internal_ackkeys() const {
  return ackkeys_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
Header::ackkeys() const {
  // @@protoc_insertion_point(field_list:Matrix.MsgService.CommonMessages.Header.ackKeys)
  return _internal_ackkeys();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
Header::_internal_mutable_ackkeys() {
  return &ackkeys_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
Header::mutable_ackkeys() {
  // @@protoc_insertion_point(field_mutable_list:Matrix.MsgService.CommonMessages.Header.ackKeys)
  return _internal_mutable_ackkeys();
}

// int32 topic = 8;
inline void Header::clear_topic() {
  topic_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::_internal_topic() const {
  return topic_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::topic() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.topic)
  return _internal_topic();
}
inline void Header::_internal_set_topic(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  topic_ = value;
}
inline void Header::set_topic(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_topic(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.topic)
}

// bool isArchived = 9;
inline void Header::clear_isarchived() {
  isarchived_ = false;
}
inline bool Header::_internal_isarchived() const {
  return isarchived_;
}
inline bool Header::isarchived() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.isArchived)
  return _internal_isarchived();
}
inline void Header::_internal_set_isarchived(bool value) {
  
  isarchived_ = value;
}
inline void Header::set_isarchived(bool value) {
  _internal_set_isarchived(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.isArchived)
}

// int32 replyMsgKey = 10;
inline void Header::clear_replymsgkey() {
  replymsgkey_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::_internal_replymsgkey() const {
  return replymsgkey_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Header::replymsgkey() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.replyMsgKey)
  return _internal_replymsgkey();
}
inline void Header::_internal_set_replymsgkey(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  replymsgkey_ = value;
}
inline void Header::set_replymsgkey(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_replymsgkey(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.replyMsgKey)
}

// bytes msg = 15;
inline void Header::clear_msg() {
  msg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Header::msg() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.msg)
  return _internal_msg();
}
inline void Header::set_msg(const std::string& value) {
  _internal_set_msg(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.msg)
}
inline std::string* Header::mutable_msg() {
  // @@protoc_insertion_point(field_mutable:Matrix.MsgService.CommonMessages.Header.msg)
  return _internal_mutable_msg();
}
inline const std::string& Header::_internal_msg() const {
  return msg_.GetNoArena();
}
inline void Header::_internal_set_msg(const std::string& value) {
  
  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Header::set_msg(std::string&& value) {
  
  msg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Matrix.MsgService.CommonMessages.Header.msg)
}
inline void Header::set_msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Matrix.MsgService.CommonMessages.Header.msg)
}
inline void Header::set_msg(const void* value, size_t size) {
  
  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Matrix.MsgService.CommonMessages.Header.msg)
}
inline std::string* Header::_internal_mutable_msg() {
  
  return msg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Header::release_msg() {
  // @@protoc_insertion_point(field_release:Matrix.MsgService.CommonMessages.Header.msg)
  
  return msg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:Matrix.MsgService.CommonMessages.Header.msg)
}

// -------------------------------------------------------------------

// NackDetails

// int32 reason = 1;
inline void NackDetails::clear_reason() {
  reason_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NackDetails::_internal_reason() const {
  return reason_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 NackDetails::reason() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.NackDetails.reason)
  return _internal_reason();
}
inline void NackDetails::_internal_set_reason(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  reason_ = value;
}
inline void NackDetails::set_reason(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_reason(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.NackDetails.reason)
}

// string details = 2;
inline void NackDetails::clear_details() {
  details_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& NackDetails::details() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.NackDetails.details)
  return _internal_details();
}
inline void NackDetails::set_details(const std::string& value) {
  _internal_set_details(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.NackDetails.details)
}
inline std::string* NackDetails::mutable_details() {
  // @@protoc_insertion_point(field_mutable:Matrix.MsgService.CommonMessages.NackDetails.details)
  return _internal_mutable_details();
}
inline const std::string& NackDetails::_internal_details() const {
  return details_.GetNoArena();
}
inline void NackDetails::_internal_set_details(const std::string& value) {
  
  details_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void NackDetails::set_details(std::string&& value) {
  
  details_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Matrix.MsgService.CommonMessages.NackDetails.details)
}
inline void NackDetails::set_details(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  details_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Matrix.MsgService.CommonMessages.NackDetails.details)
}
inline void NackDetails::set_details(const char* value, size_t size) {
  
  details_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Matrix.MsgService.CommonMessages.NackDetails.details)
}
inline std::string* NackDetails::_internal_mutable_details() {
  
  return details_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* NackDetails::release_details() {
  // @@protoc_insertion_point(field_release:Matrix.MsgService.CommonMessages.NackDetails.details)
  
  return details_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void NackDetails::set_allocated_details(std::string* details) {
  if (details != nullptr) {
    
  } else {
    
  }
  details_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), details);
  // @@protoc_insertion_point(field_set_allocated:Matrix.MsgService.CommonMessages.NackDetails.details)
}

// -------------------------------------------------------------------

// Logon

// int32 clientType = 1;
inline void Logon::clear_clienttype() {
  clienttype_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Logon::_internal_clienttype() const {
  return clienttype_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Logon::clienttype() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Logon.clientType)
  return _internal_clienttype();
}
inline void Logon::_internal_set_clienttype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  clienttype_ = value;
}
inline void Logon::set_clienttype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_clienttype(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Logon.clientType)
}

// int32 clientID = 2;
inline void Logon::clear_clientid() {
  clientid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Logon::_internal_clientid() const {
  return clientid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Logon::clientid() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Logon.clientID)
  return _internal_clientid();
}
inline void Logon::_internal_set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  clientid_ = value;
}
inline void Logon::set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Logon.clientID)
}

// -------------------------------------------------------------------

// Subscribe

// int32 clientType = 1;
inline void Subscribe::clear_clienttype() {
  clienttype_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Subscribe::_internal_clienttype() const {
  return clienttype_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Subscribe::clienttype() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Subscribe.clientType)
  return _internal_clienttype();
}
inline void Subscribe::_internal_set_clienttype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  clienttype_ = value;
}
inline void Subscribe::set_clienttype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_clienttype(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Subscribe.clientType)
}

// int32 clientID = 2;
inline void Subscribe::clear_clientid() {
  clientid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Subscribe::_internal_clientid() const {
  return clientid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Subscribe::clientid() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Subscribe.clientID)
  return _internal_clientid();
}
inline void Subscribe::_internal_set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  clientid_ = value;
}
inline void Subscribe::set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Subscribe.clientID)
}

// int32 topic = 3;
inline void Subscribe::clear_topic() {
  topic_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Subscribe::_internal_topic() const {
  return topic_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Subscribe::topic() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Subscribe.topic)
  return _internal_topic();
}
inline void Subscribe::_internal_set_topic(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  topic_ = value;
}
inline void Subscribe::set_topic(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_topic(value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Subscribe.topic)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace CommonMessages
}  // namespace MsgService
}  // namespace Matrix

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Matrix::MsgService::CommonMessages::MsgType> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_CommonMessages_2eproto
