#ifdef _WIN32
#pragma warning( push )
#pragma warning( disable: 4251 4100 4146 4018 4267 4244 4127 26495 26812 6387 6385)
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMessages.proto

#include "CommonMessages.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace Matrix {
namespace MsgService {
namespace CommonMessages {
constexpr Header::Header(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : ackkeys_()
  , _ackkeys_cached_byte_size_()
  , msg_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , msgtypeid_(0)

  , msgkey_(0)
  , origclienttype_(0)
  , origclientid_(0)
  , destclienttype_(0)
  , destclientid_(0)
  , topic_(0)
  , isarchived_(false)
  , replymsgkey_(0){}
struct HeaderDefaultTypeInternal {
  constexpr HeaderDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~HeaderDefaultTypeInternal() {}
  union {
    Header _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT HeaderDefaultTypeInternal _Header_default_instance_;
constexpr NackDetails::NackDetails(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : details_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , reason_(0){}
struct NackDetailsDefaultTypeInternal {
  constexpr NackDetailsDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~NackDetailsDefaultTypeInternal() {}
  union {
    NackDetails _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT NackDetailsDefaultTypeInternal _NackDetails_default_instance_;
constexpr Logon::Logon(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : clienttype_(0)
  , clientid_(0){}
struct LogonDefaultTypeInternal {
  constexpr LogonDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~LogonDefaultTypeInternal() {}
  union {
    Logon _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT LogonDefaultTypeInternal _Logon_default_instance_;
constexpr Subscribe::Subscribe(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : clienttype_(0)
  , clientid_(0)
  , topic_(0){}
struct SubscribeDefaultTypeInternal {
  constexpr SubscribeDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SubscribeDefaultTypeInternal() {}
  union {
    Subscribe _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SubscribeDefaultTypeInternal _Subscribe_default_instance_;
}  // namespace CommonMessages
}  // namespace MsgService
}  // namespace Matrix
namespace Matrix {
namespace MsgService {
namespace CommonMessages {
bool MsgType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 100:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> MsgType_strings[8] = {};

static const char MsgType_names[] =
  "ACK"
  "CUSTOM"
  "INVALID_MSG_TYPE"
  "LOGOFF"
  "LOGON"
  "NACK"
  "SUBSCRIBE"
  "UNSUBSCRIBE";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry MsgType_entries[] = {
  { {MsgType_names + 0, 3}, 1 },
  { {MsgType_names + 3, 6}, 100 },
  { {MsgType_names + 9, 16}, 0 },
  { {MsgType_names + 25, 6}, 3 },
  { {MsgType_names + 31, 5}, 2 },
  { {MsgType_names + 36, 4}, 6 },
  { {MsgType_names + 40, 9}, 4 },
  { {MsgType_names + 49, 11}, 5 },
};

static const int MsgType_entries_by_number[] = {
  2, // 0 -> INVALID_MSG_TYPE
  0, // 1 -> ACK
  4, // 2 -> LOGON
  3, // 3 -> LOGOFF
  6, // 4 -> SUBSCRIBE
  7, // 5 -> UNSUBSCRIBE
  5, // 6 -> NACK
  1, // 100 -> CUSTOM
};

const std::string& MsgType_Name(
    MsgType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          MsgType_entries,
          MsgType_entries_by_number,
          8, MsgType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      MsgType_entries,
      MsgType_entries_by_number,
      8, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     MsgType_strings[idx].get();
}
bool MsgType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MsgType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      MsgType_entries, 8, name, &int_value);
  if (success) {
    *value = static_cast<MsgType>(int_value);
  }
  return success;
}

// ===================================================================

class Header::_Internal {
 public:
};

Header::Header(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena),
  ackkeys_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Matrix.MsgService.CommonMessages.Header)
}
Header::Header(const Header& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      ackkeys_(from.ackkeys_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  msg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_msg().empty()) {
    msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_msg(), 
      GetArena());
  }
  ::memcpy(&msgtypeid_, &from.msgtypeid_,
    static_cast<size_t>(reinterpret_cast<char*>(&replymsgkey_) -
    reinterpret_cast<char*>(&msgtypeid_)) + sizeof(replymsgkey_));
  // @@protoc_insertion_point(copy_constructor:Matrix.MsgService.CommonMessages.Header)
}

void Header::SharedCtor() {
msg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&msgtypeid_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&replymsgkey_) -
    reinterpret_cast<char*>(&msgtypeid_)) + sizeof(replymsgkey_));
}

Header::~Header() {
  // @@protoc_insertion_point(destructor:Matrix.MsgService.CommonMessages.Header)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void Header::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  msg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Header::ArenaDtor(void* object) {
  Header* _this = reinterpret_cast< Header* >(object);
  (void)_this;
}
void Header::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Header::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Header::Clear() {
// @@protoc_insertion_point(message_clear_start:Matrix.MsgService.CommonMessages.Header)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ackkeys_.Clear();
  msg_.ClearToEmpty();
  ::memset(&msgtypeid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&replymsgkey_) -
      reinterpret_cast<char*>(&msgtypeid_)) + sizeof(replymsgkey_));
  _internal_metadata_.Clear<std::string>();
}

const char* Header::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .Matrix.MsgService.CommonMessages.MsgType msgTypeID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_msgtypeid(static_cast<::Matrix::MsgService::CommonMessages::MsgType>(val));
        } else goto handle_unusual;
        continue;
      // int32 msgKey = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          msgkey_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 origClientType = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          origclienttype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 origClientID = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          origclientid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 destClientType = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          destclienttype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 destClientID = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          destclientid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated int32 ackKeys = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_ackkeys(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56) {
          _internal_add_ackkeys(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 topic = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          topic_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool isArchived = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          isarchived_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 replyMsgKey = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          replymsgkey_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes msg = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 122)) {
          auto str = _internal_mutable_msg();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Header::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Matrix.MsgService.CommonMessages.Header)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Matrix.MsgService.CommonMessages.MsgType msgTypeID = 1;
  if (this->msgtypeid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_msgtypeid(), target);
  }

  // int32 msgKey = 2;
  if (this->msgkey() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_msgkey(), target);
  }

  // int32 origClientType = 3;
  if (this->origclienttype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_origclienttype(), target);
  }

  // int32 origClientID = 4;
  if (this->origclientid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_origclientid(), target);
  }

  // int32 destClientType = 5;
  if (this->destclienttype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_destclienttype(), target);
  }

  // int32 destClientID = 6;
  if (this->destclientid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(6, this->_internal_destclientid(), target);
  }

  // repeated int32 ackKeys = 7;
  {
    int byte_size = _ackkeys_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          7, _internal_ackkeys(), byte_size, target);
    }
  }

  // int32 topic = 8;
  if (this->topic() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(8, this->_internal_topic(), target);
  }

  // bool isArchived = 9;
  if (this->isarchived() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(9, this->_internal_isarchived(), target);
  }

  // int32 replyMsgKey = 10;
  if (this->replymsgkey() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(10, this->_internal_replymsgkey(), target);
  }

  // bytes msg = 15;
  if (this->msg().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        15, this->_internal_msg(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Matrix.MsgService.CommonMessages.Header)
  return target;
}

size_t Header::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Matrix.MsgService.CommonMessages.Header)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 ackKeys = 7;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int32Size(this->ackkeys_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _ackkeys_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // bytes msg = 15;
  if (this->msg().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_msg());
  }

  // .Matrix.MsgService.CommonMessages.MsgType msgTypeID = 1;
  if (this->msgtypeid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_msgtypeid());
  }

  // int32 msgKey = 2;
  if (this->msgkey() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_msgkey());
  }

  // int32 origClientType = 3;
  if (this->origclienttype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_origclienttype());
  }

  // int32 origClientID = 4;
  if (this->origclientid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_origclientid());
  }

  // int32 destClientType = 5;
  if (this->destclienttype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_destclienttype());
  }

  // int32 destClientID = 6;
  if (this->destclientid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_destclientid());
  }

  // int32 topic = 8;
  if (this->topic() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_topic());
  }

  // bool isArchived = 9;
  if (this->isarchived() != 0) {
    total_size += 1 + 1;
  }

  // int32 replyMsgKey = 10;
  if (this->replymsgkey() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_replymsgkey());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Header::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const Header*>(
      &from));
}

void Header::MergeFrom(const Header& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Matrix.MsgService.CommonMessages.Header)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  ackkeys_.MergeFrom(from.ackkeys_);
  if (from.msg().size() > 0) {
    _internal_set_msg(from._internal_msg());
  }
  if (from.msgtypeid() != 0) {
    _internal_set_msgtypeid(from._internal_msgtypeid());
  }
  if (from.msgkey() != 0) {
    _internal_set_msgkey(from._internal_msgkey());
  }
  if (from.origclienttype() != 0) {
    _internal_set_origclienttype(from._internal_origclienttype());
  }
  if (from.origclientid() != 0) {
    _internal_set_origclientid(from._internal_origclientid());
  }
  if (from.destclienttype() != 0) {
    _internal_set_destclienttype(from._internal_destclienttype());
  }
  if (from.destclientid() != 0) {
    _internal_set_destclientid(from._internal_destclientid());
  }
  if (from.topic() != 0) {
    _internal_set_topic(from._internal_topic());
  }
  if (from.isarchived() != 0) {
    _internal_set_isarchived(from._internal_isarchived());
  }
  if (from.replymsgkey() != 0) {
    _internal_set_replymsgkey(from._internal_replymsgkey());
  }
}

void Header::CopyFrom(const Header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Matrix.MsgService.CommonMessages.Header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Header::IsInitialized() const {
  return true;
}

void Header::InternalSwap(Header* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  ackkeys_.InternalSwap(&other->ackkeys_);
  msg_.Swap(&other->msg_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Header, replymsgkey_)
      + sizeof(Header::replymsgkey_)
      - PROTOBUF_FIELD_OFFSET(Header, msgtypeid_)>(
          reinterpret_cast<char*>(&msgtypeid_),
          reinterpret_cast<char*>(&other->msgtypeid_));
}

std::string Header::GetTypeName() const {
  return "Matrix.MsgService.CommonMessages.Header";
}


// ===================================================================

class NackDetails::_Internal {
 public:
};

NackDetails::NackDetails(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Matrix.MsgService.CommonMessages.NackDetails)
}
NackDetails::NackDetails(const NackDetails& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  details_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_details().empty()) {
    details_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_details(), 
      GetArena());
  }
  reason_ = from.reason_;
  // @@protoc_insertion_point(copy_constructor:Matrix.MsgService.CommonMessages.NackDetails)
}

void NackDetails::SharedCtor() {
details_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
reason_ = 0;
}

NackDetails::~NackDetails() {
  // @@protoc_insertion_point(destructor:Matrix.MsgService.CommonMessages.NackDetails)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void NackDetails::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  details_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NackDetails::ArenaDtor(void* object) {
  NackDetails* _this = reinterpret_cast< NackDetails* >(object);
  (void)_this;
}
void NackDetails::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NackDetails::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void NackDetails::Clear() {
// @@protoc_insertion_point(message_clear_start:Matrix.MsgService.CommonMessages.NackDetails)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  details_.ClearToEmpty();
  reason_ = 0;
  _internal_metadata_.Clear<std::string>();
}

const char* NackDetails::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 reason = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          reason_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string details = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_details();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, nullptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NackDetails::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Matrix.MsgService.CommonMessages.NackDetails)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 reason = 1;
  if (this->reason() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_reason(), target);
  }

  // string details = 2;
  if (this->details().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_details().data(), static_cast<int>(this->_internal_details().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Matrix.MsgService.CommonMessages.NackDetails.details");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_details(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Matrix.MsgService.CommonMessages.NackDetails)
  return target;
}

size_t NackDetails::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Matrix.MsgService.CommonMessages.NackDetails)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string details = 2;
  if (this->details().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_details());
  }

  // int32 reason = 1;
  if (this->reason() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_reason());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NackDetails::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const NackDetails*>(
      &from));
}

void NackDetails::MergeFrom(const NackDetails& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Matrix.MsgService.CommonMessages.NackDetails)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.details().size() > 0) {
    _internal_set_details(from._internal_details());
  }
  if (from.reason() != 0) {
    _internal_set_reason(from._internal_reason());
  }
}

void NackDetails::CopyFrom(const NackDetails& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Matrix.MsgService.CommonMessages.NackDetails)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NackDetails::IsInitialized() const {
  return true;
}

void NackDetails::InternalSwap(NackDetails* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  details_.Swap(&other->details_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(reason_, other->reason_);
}

std::string NackDetails::GetTypeName() const {
  return "Matrix.MsgService.CommonMessages.NackDetails";
}


// ===================================================================

class Logon::_Internal {
 public:
};

Logon::Logon(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Matrix.MsgService.CommonMessages.Logon)
}
Logon::Logon(const Logon& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&clienttype_, &from.clienttype_,
    static_cast<size_t>(reinterpret_cast<char*>(&clientid_) -
    reinterpret_cast<char*>(&clienttype_)) + sizeof(clientid_));
  // @@protoc_insertion_point(copy_constructor:Matrix.MsgService.CommonMessages.Logon)
}

void Logon::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&clienttype_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&clientid_) -
    reinterpret_cast<char*>(&clienttype_)) + sizeof(clientid_));
}

Logon::~Logon() {
  // @@protoc_insertion_point(destructor:Matrix.MsgService.CommonMessages.Logon)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void Logon::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Logon::ArenaDtor(void* object) {
  Logon* _this = reinterpret_cast< Logon* >(object);
  (void)_this;
}
void Logon::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Logon::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Logon::Clear() {
// @@protoc_insertion_point(message_clear_start:Matrix.MsgService.CommonMessages.Logon)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&clienttype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&clientid_) -
      reinterpret_cast<char*>(&clienttype_)) + sizeof(clientid_));
  _internal_metadata_.Clear<std::string>();
}

const char* Logon::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 clientType = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          clienttype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 clientID = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          clientid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Logon::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Matrix.MsgService.CommonMessages.Logon)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 clientType = 1;
  if (this->clienttype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_clienttype(), target);
  }

  // int32 clientID = 2;
  if (this->clientid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_clientid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Matrix.MsgService.CommonMessages.Logon)
  return target;
}

size_t Logon::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Matrix.MsgService.CommonMessages.Logon)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 clientType = 1;
  if (this->clienttype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_clienttype());
  }

  // int32 clientID = 2;
  if (this->clientid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_clientid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Logon::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const Logon*>(
      &from));
}

void Logon::MergeFrom(const Logon& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Matrix.MsgService.CommonMessages.Logon)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.clienttype() != 0) {
    _internal_set_clienttype(from._internal_clienttype());
  }
  if (from.clientid() != 0) {
    _internal_set_clientid(from._internal_clientid());
  }
}

void Logon::CopyFrom(const Logon& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Matrix.MsgService.CommonMessages.Logon)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Logon::IsInitialized() const {
  return true;
}

void Logon::InternalSwap(Logon* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Logon, clientid_)
      + sizeof(Logon::clientid_)
      - PROTOBUF_FIELD_OFFSET(Logon, clienttype_)>(
          reinterpret_cast<char*>(&clienttype_),
          reinterpret_cast<char*>(&other->clienttype_));
}

std::string Logon::GetTypeName() const {
  return "Matrix.MsgService.CommonMessages.Logon";
}


// ===================================================================

class Subscribe::_Internal {
 public:
};

Subscribe::Subscribe(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Matrix.MsgService.CommonMessages.Subscribe)
}
Subscribe::Subscribe(const Subscribe& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&clienttype_, &from.clienttype_,
    static_cast<size_t>(reinterpret_cast<char*>(&topic_) -
    reinterpret_cast<char*>(&clienttype_)) + sizeof(topic_));
  // @@protoc_insertion_point(copy_constructor:Matrix.MsgService.CommonMessages.Subscribe)
}

void Subscribe::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&clienttype_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&topic_) -
    reinterpret_cast<char*>(&clienttype_)) + sizeof(topic_));
}

Subscribe::~Subscribe() {
  // @@protoc_insertion_point(destructor:Matrix.MsgService.CommonMessages.Subscribe)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void Subscribe::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Subscribe::ArenaDtor(void* object) {
  Subscribe* _this = reinterpret_cast< Subscribe* >(object);
  (void)_this;
}
void Subscribe::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Subscribe::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Subscribe::Clear() {
// @@protoc_insertion_point(message_clear_start:Matrix.MsgService.CommonMessages.Subscribe)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&clienttype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&topic_) -
      reinterpret_cast<char*>(&clienttype_)) + sizeof(topic_));
  _internal_metadata_.Clear<std::string>();
}

const char* Subscribe::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 clientType = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          clienttype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 clientID = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          clientid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 topic = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          topic_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Subscribe::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Matrix.MsgService.CommonMessages.Subscribe)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 clientType = 1;
  if (this->clienttype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_clienttype(), target);
  }

  // int32 clientID = 2;
  if (this->clientid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_clientid(), target);
  }

  // int32 topic = 3;
  if (this->topic() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_topic(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Matrix.MsgService.CommonMessages.Subscribe)
  return target;
}

size_t Subscribe::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Matrix.MsgService.CommonMessages.Subscribe)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 clientType = 1;
  if (this->clienttype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_clienttype());
  }

  // int32 clientID = 2;
  if (this->clientid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_clientid());
  }

  // int32 topic = 3;
  if (this->topic() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_topic());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Subscribe::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const Subscribe*>(
      &from));
}

void Subscribe::MergeFrom(const Subscribe& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Matrix.MsgService.CommonMessages.Subscribe)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.clienttype() != 0) {
    _internal_set_clienttype(from._internal_clienttype());
  }
  if (from.clientid() != 0) {
    _internal_set_clientid(from._internal_clientid());
  }
  if (from.topic() != 0) {
    _internal_set_topic(from._internal_topic());
  }
}

void Subscribe::CopyFrom(const Subscribe& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Matrix.MsgService.CommonMessages.Subscribe)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Subscribe::IsInitialized() const {
  return true;
}

void Subscribe::InternalSwap(Subscribe* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Subscribe, topic_)
      + sizeof(Subscribe::topic_)
      - PROTOBUF_FIELD_OFFSET(Subscribe, clienttype_)>(
          reinterpret_cast<char*>(&clienttype_),
          reinterpret_cast<char*>(&other->clienttype_));
}

std::string Subscribe::GetTypeName() const {
  return "Matrix.MsgService.CommonMessages.Subscribe";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace CommonMessages
}  // namespace MsgService
}  // namespace Matrix
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Matrix::MsgService::CommonMessages::Header* Arena::CreateMaybeMessage< ::Matrix::MsgService::CommonMessages::Header >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Matrix::MsgService::CommonMessages::Header >(arena);
}
template<> PROTOBUF_NOINLINE ::Matrix::MsgService::CommonMessages::NackDetails* Arena::CreateMaybeMessage< ::Matrix::MsgService::CommonMessages::NackDetails >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Matrix::MsgService::CommonMessages::NackDetails >(arena);
}
template<> PROTOBUF_NOINLINE ::Matrix::MsgService::CommonMessages::Logon* Arena::CreateMaybeMessage< ::Matrix::MsgService::CommonMessages::Logon >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Matrix::MsgService::CommonMessages::Logon >(arena);
}
template<> PROTOBUF_NOINLINE ::Matrix::MsgService::CommonMessages::Subscribe* Arena::CreateMaybeMessage< ::Matrix::MsgService::CommonMessages::Subscribe >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Matrix::MsgService::CommonMessages::Subscribe >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
#ifdef _WIN32
#pragma warning( pop )
#endif
