#include "stdafx.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMessages.proto

#ifndef PROTOBUF_CommonMessages_2eproto__INCLUDED
#define PROTOBUF_CommonMessages_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

namespace protobuf_CommonMessages_2eproto {
// Internal implementation detail -- do not use these members.
struct COMMONMESSAGES_API TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void COMMONMESSAGES_API InitDefaultsHeaderImpl();
void COMMONMESSAGES_API InitDefaultsHeader();
void COMMONMESSAGES_API InitDefaultsLogonImpl();
void COMMONMESSAGES_API InitDefaultsLogon();
void COMMONMESSAGES_API InitDefaultsSubscribeImpl();
void COMMONMESSAGES_API InitDefaultsSubscribe();
inline void COMMONMESSAGES_API InitDefaults() {
  InitDefaultsHeader();
  InitDefaultsLogon();
  InitDefaultsSubscribe();
}
}  // namespace protobuf_CommonMessages_2eproto
namespace Matrix {
namespace MsgService {
namespace CommonMessages {
class Header;
class HeaderDefaultTypeInternal;
COMMONMESSAGES_API extern HeaderDefaultTypeInternal _Header_default_instance_;
class Logon;
class LogonDefaultTypeInternal;
COMMONMESSAGES_API extern LogonDefaultTypeInternal _Logon_default_instance_;
class Subscribe;
class SubscribeDefaultTypeInternal;
COMMONMESSAGES_API extern SubscribeDefaultTypeInternal _Subscribe_default_instance_;
}  // namespace CommonMessages
}  // namespace MsgService
}  // namespace Matrix
namespace Matrix {
namespace MsgService {
namespace CommonMessages {

enum MsgType {
  INVALID_MSG_TYPE = 0,
  ACK = 1,
  LOGON = 2,
  LOGOFF = 3,
  SUBSCRIBE = 4,
  UNSUBSCRIBE = 5,
  CUSTOM = 100,
  MsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
COMMONMESSAGES_API bool MsgType_IsValid(int value);
const MsgType MsgType_MIN = INVALID_MSG_TYPE;
const MsgType MsgType_MAX = CUSTOM;
const int MsgType_ARRAYSIZE = MsgType_MAX + 1;

// ===================================================================

class COMMONMESSAGES_API Header : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Matrix.MsgService.CommonMessages.Header) */ {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Header(Header&& from) noexcept
    : Header() {
    *this = ::std::move(from);
  }

  inline Header& operator=(Header&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const Header& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Header* internal_default_instance() {
    return reinterpret_cast<const Header*>(
               &_Header_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Header* other);
  friend void swap(Header& a, Header& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Header* New() const PROTOBUF_FINAL { return New(NULL); }

  Header* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Header* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 ackKeys = 7;
  int ackkeys_size() const;
  void clear_ackkeys();
  static const int kAckKeysFieldNumber = 7;
  ::google::protobuf::int32 ackkeys(int index) const;
  void set_ackkeys(int index, ::google::protobuf::int32 value);
  void add_ackkeys(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      ackkeys() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_ackkeys();

  // bytes msg = 15;
  void clear_msg();
  static const int kMsgFieldNumber = 15;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const void* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // .Matrix.MsgService.CommonMessages.MsgType msgTypeID = 1;
  void clear_msgtypeid();
  static const int kMsgTypeIDFieldNumber = 1;
  ::Matrix::MsgService::CommonMessages::MsgType msgtypeid() const;
  void set_msgtypeid(::Matrix::MsgService::CommonMessages::MsgType value);

  // int32 msgKey = 2;
  void clear_msgkey();
  static const int kMsgKeyFieldNumber = 2;
  ::google::protobuf::int32 msgkey() const;
  void set_msgkey(::google::protobuf::int32 value);

  // int32 origClientType = 3;
  void clear_origclienttype();
  static const int kOrigClientTypeFieldNumber = 3;
  ::google::protobuf::int32 origclienttype() const;
  void set_origclienttype(::google::protobuf::int32 value);

  // int32 origClientID = 4;
  void clear_origclientid();
  static const int kOrigClientIDFieldNumber = 4;
  ::google::protobuf::int32 origclientid() const;
  void set_origclientid(::google::protobuf::int32 value);

  // int32 destClientType = 5;
  void clear_destclienttype();
  static const int kDestClientTypeFieldNumber = 5;
  ::google::protobuf::int32 destclienttype() const;
  void set_destclienttype(::google::protobuf::int32 value);

  // int32 destClientID = 6;
  void clear_destclientid();
  static const int kDestClientIDFieldNumber = 6;
  ::google::protobuf::int32 destclientid() const;
  void set_destclientid(::google::protobuf::int32 value);

  // int32 topic = 8;
  void clear_topic();
  static const int kTopicFieldNumber = 8;
  ::google::protobuf::int32 topic() const;
  void set_topic(::google::protobuf::int32 value);

  // bool isArchived = 9;
  void clear_isarchived();
  static const int kIsArchivedFieldNumber = 9;
  bool isarchived() const;
  void set_isarchived(bool value);

  // int32 replyMsgKey = 10;
  void clear_replymsgkey();
  static const int kReplyMsgKeyFieldNumber = 10;
  ::google::protobuf::int32 replymsgkey() const;
  void set_replymsgkey(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Matrix.MsgService.CommonMessages.Header)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > ackkeys_;
  mutable int _ackkeys_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  int msgtypeid_;
  ::google::protobuf::int32 msgkey_;
  ::google::protobuf::int32 origclienttype_;
  ::google::protobuf::int32 origclientid_;
  ::google::protobuf::int32 destclienttype_;
  ::google::protobuf::int32 destclientid_;
  ::google::protobuf::int32 topic_;
  bool isarchived_;
  ::google::protobuf::int32 replymsgkey_;
  mutable int _cached_size_;
  friend struct ::protobuf_CommonMessages_2eproto::TableStruct;
  friend void ::protobuf_CommonMessages_2eproto::InitDefaultsHeaderImpl();
};
// -------------------------------------------------------------------

class COMMONMESSAGES_API Logon : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Matrix.MsgService.CommonMessages.Logon) */ {
 public:
  Logon();
  virtual ~Logon();

  Logon(const Logon& from);

  inline Logon& operator=(const Logon& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Logon(Logon&& from) noexcept
    : Logon() {
    *this = ::std::move(from);
  }

  inline Logon& operator=(Logon&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const Logon& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Logon* internal_default_instance() {
    return reinterpret_cast<const Logon*>(
               &_Logon_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Logon* other);
  friend void swap(Logon& a, Logon& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Logon* New() const PROTOBUF_FINAL { return New(NULL); }

  Logon* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const Logon& from);
  void MergeFrom(const Logon& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Logon* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 clientType = 1;
  void clear_clienttype();
  static const int kClientTypeFieldNumber = 1;
  ::google::protobuf::int32 clienttype() const;
  void set_clienttype(::google::protobuf::int32 value);

  // int32 clientID = 2;
  void clear_clientid();
  static const int kClientIDFieldNumber = 2;
  ::google::protobuf::int32 clientid() const;
  void set_clientid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Matrix.MsgService.CommonMessages.Logon)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::int32 clienttype_;
  ::google::protobuf::int32 clientid_;
  mutable int _cached_size_;
  friend struct ::protobuf_CommonMessages_2eproto::TableStruct;
  friend void ::protobuf_CommonMessages_2eproto::InitDefaultsLogonImpl();
};
// -------------------------------------------------------------------

class COMMONMESSAGES_API Subscribe : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Matrix.MsgService.CommonMessages.Subscribe) */ {
 public:
  Subscribe();
  virtual ~Subscribe();

  Subscribe(const Subscribe& from);

  inline Subscribe& operator=(const Subscribe& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Subscribe(Subscribe&& from) noexcept
    : Subscribe() {
    *this = ::std::move(from);
  }

  inline Subscribe& operator=(Subscribe&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const Subscribe& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Subscribe* internal_default_instance() {
    return reinterpret_cast<const Subscribe*>(
               &_Subscribe_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Subscribe* other);
  friend void swap(Subscribe& a, Subscribe& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Subscribe* New() const PROTOBUF_FINAL { return New(NULL); }

  Subscribe* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const Subscribe& from);
  void MergeFrom(const Subscribe& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Subscribe* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 clientType = 1;
  void clear_clienttype();
  static const int kClientTypeFieldNumber = 1;
  ::google::protobuf::int32 clienttype() const;
  void set_clienttype(::google::protobuf::int32 value);

  // int32 clientID = 2;
  void clear_clientid();
  static const int kClientIDFieldNumber = 2;
  ::google::protobuf::int32 clientid() const;
  void set_clientid(::google::protobuf::int32 value);

  // int32 topic = 3;
  void clear_topic();
  static const int kTopicFieldNumber = 3;
  ::google::protobuf::int32 topic() const;
  void set_topic(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Matrix.MsgService.CommonMessages.Subscribe)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::int32 clienttype_;
  ::google::protobuf::int32 clientid_;
  ::google::protobuf::int32 topic_;
  mutable int _cached_size_;
  friend struct ::protobuf_CommonMessages_2eproto::TableStruct;
  friend void ::protobuf_CommonMessages_2eproto::InitDefaultsSubscribeImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Header

// .Matrix.MsgService.CommonMessages.MsgType msgTypeID = 1;
inline void Header::clear_msgtypeid() {
  msgtypeid_ = 0;
}
inline ::Matrix::MsgService::CommonMessages::MsgType Header::msgtypeid() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.msgTypeID)
  return static_cast< ::Matrix::MsgService::CommonMessages::MsgType >(msgtypeid_);
}
inline void Header::set_msgtypeid(::Matrix::MsgService::CommonMessages::MsgType value) {
  
  msgtypeid_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.msgTypeID)
}

// int32 msgKey = 2;
inline void Header::clear_msgkey() {
  msgkey_ = 0;
}
inline ::google::protobuf::int32 Header::msgkey() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.msgKey)
  return msgkey_;
}
inline void Header::set_msgkey(::google::protobuf::int32 value) {
  
  msgkey_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.msgKey)
}

// int32 origClientType = 3;
inline void Header::clear_origclienttype() {
  origclienttype_ = 0;
}
inline ::google::protobuf::int32 Header::origclienttype() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.origClientType)
  return origclienttype_;
}
inline void Header::set_origclienttype(::google::protobuf::int32 value) {
  
  origclienttype_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.origClientType)
}

// int32 origClientID = 4;
inline void Header::clear_origclientid() {
  origclientid_ = 0;
}
inline ::google::protobuf::int32 Header::origclientid() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.origClientID)
  return origclientid_;
}
inline void Header::set_origclientid(::google::protobuf::int32 value) {
  
  origclientid_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.origClientID)
}

// int32 destClientType = 5;
inline void Header::clear_destclienttype() {
  destclienttype_ = 0;
}
inline ::google::protobuf::int32 Header::destclienttype() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.destClientType)
  return destclienttype_;
}
inline void Header::set_destclienttype(::google::protobuf::int32 value) {
  
  destclienttype_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.destClientType)
}

// int32 destClientID = 6;
inline void Header::clear_destclientid() {
  destclientid_ = 0;
}
inline ::google::protobuf::int32 Header::destclientid() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.destClientID)
  return destclientid_;
}
inline void Header::set_destclientid(::google::protobuf::int32 value) {
  
  destclientid_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.destClientID)
}

// repeated int32 ackKeys = 7;
inline int Header::ackkeys_size() const {
  return ackkeys_.size();
}
inline void Header::clear_ackkeys() {
  ackkeys_.Clear();
}
inline ::google::protobuf::int32 Header::ackkeys(int index) const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.ackKeys)
  return ackkeys_.Get(index);
}
inline void Header::set_ackkeys(int index, ::google::protobuf::int32 value) {
  ackkeys_.Set(index, value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.ackKeys)
}
inline void Header::add_ackkeys(::google::protobuf::int32 value) {
  ackkeys_.Add(value);
  // @@protoc_insertion_point(field_add:Matrix.MsgService.CommonMessages.Header.ackKeys)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Header::ackkeys() const {
  // @@protoc_insertion_point(field_list:Matrix.MsgService.CommonMessages.Header.ackKeys)
  return ackkeys_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Header::mutable_ackkeys() {
  // @@protoc_insertion_point(field_mutable_list:Matrix.MsgService.CommonMessages.Header.ackKeys)
  return &ackkeys_;
}

// int32 topic = 8;
inline void Header::clear_topic() {
  topic_ = 0;
}
inline ::google::protobuf::int32 Header::topic() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.topic)
  return topic_;
}
inline void Header::set_topic(::google::protobuf::int32 value) {
  
  topic_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.topic)
}

// bool isArchived = 9;
inline void Header::clear_isarchived() {
  isarchived_ = false;
}
inline bool Header::isarchived() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.isArchived)
  return isarchived_;
}
inline void Header::set_isarchived(bool value) {
  
  isarchived_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.isArchived)
}

// int32 replyMsgKey = 10;
inline void Header::clear_replymsgkey() {
  replymsgkey_ = 0;
}
inline ::google::protobuf::int32 Header::replymsgkey() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.replyMsgKey)
  return replymsgkey_;
}
inline void Header::set_replymsgkey(::google::protobuf::int32 value) {
  
  replymsgkey_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.replyMsgKey)
}

// bytes msg = 15;
inline void Header::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Header::msg() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Header.msg)
  return msg_.GetNoArena();
}
inline void Header::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Header.msg)
}
#if LANG_CXX11
inline void Header::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Matrix.MsgService.CommonMessages.Header.msg)
}
#endif
inline void Header::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Matrix.MsgService.CommonMessages.Header.msg)
}
inline void Header::set_msg(const void* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Matrix.MsgService.CommonMessages.Header.msg)
}
inline ::std::string* Header::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:Matrix.MsgService.CommonMessages.Header.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Header::release_msg() {
  // @@protoc_insertion_point(field_release:Matrix.MsgService.CommonMessages.Header.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:Matrix.MsgService.CommonMessages.Header.msg)
}

// -------------------------------------------------------------------

// Logon

// int32 clientType = 1;
inline void Logon::clear_clienttype() {
  clienttype_ = 0;
}
inline ::google::protobuf::int32 Logon::clienttype() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Logon.clientType)
  return clienttype_;
}
inline void Logon::set_clienttype(::google::protobuf::int32 value) {
  
  clienttype_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Logon.clientType)
}

// int32 clientID = 2;
inline void Logon::clear_clientid() {
  clientid_ = 0;
}
inline ::google::protobuf::int32 Logon::clientid() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Logon.clientID)
  return clientid_;
}
inline void Logon::set_clientid(::google::protobuf::int32 value) {
  
  clientid_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Logon.clientID)
}

// -------------------------------------------------------------------

// Subscribe

// int32 clientType = 1;
inline void Subscribe::clear_clienttype() {
  clienttype_ = 0;
}
inline ::google::protobuf::int32 Subscribe::clienttype() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Subscribe.clientType)
  return clienttype_;
}
inline void Subscribe::set_clienttype(::google::protobuf::int32 value) {
  
  clienttype_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Subscribe.clientType)
}

// int32 clientID = 2;
inline void Subscribe::clear_clientid() {
  clientid_ = 0;
}
inline ::google::protobuf::int32 Subscribe::clientid() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Subscribe.clientID)
  return clientid_;
}
inline void Subscribe::set_clientid(::google::protobuf::int32 value) {
  
  clientid_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Subscribe.clientID)
}

// int32 topic = 3;
inline void Subscribe::clear_topic() {
  topic_ = 0;
}
inline ::google::protobuf::int32 Subscribe::topic() const {
  // @@protoc_insertion_point(field_get:Matrix.MsgService.CommonMessages.Subscribe.topic)
  return topic_;
}
inline void Subscribe::set_topic(::google::protobuf::int32 value) {
  
  topic_ = value;
  // @@protoc_insertion_point(field_set:Matrix.MsgService.CommonMessages.Subscribe.topic)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace CommonMessages
}  // namespace MsgService
}  // namespace Matrix

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Matrix::MsgService::CommonMessages::MsgType> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CommonMessages_2eproto__INCLUDED
