#ifdef _WIN32
#pragma warning( push )
#pragma warning( disable: 4251 4100 4146)
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMessages.proto

#include "CommonMessages.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace Matrix {
namespace MsgService {
namespace CommonMessages {
class HeaderDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Header>
      _instance;
} _Header_default_instance_;
class NackDetailsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NackDetails>
      _instance;
} _NackDetails_default_instance_;
class LogonDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Logon>
      _instance;
} _Logon_default_instance_;
class SubscribeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Subscribe>
      _instance;
} _Subscribe_default_instance_;
}  // namespace CommonMessages
}  // namespace MsgService
}  // namespace Matrix
namespace protobuf_CommonMessages_2eproto {
void InitDefaultsHeaderImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::Matrix::MsgService::CommonMessages::_Header_default_instance_;
    new (ptr) ::Matrix::MsgService::CommonMessages::Header();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Matrix::MsgService::CommonMessages::Header::InitAsDefaultInstance();
}

void InitDefaultsHeader() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsHeaderImpl);
}

void InitDefaultsNackDetailsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::Matrix::MsgService::CommonMessages::_NackDetails_default_instance_;
    new (ptr) ::Matrix::MsgService::CommonMessages::NackDetails();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Matrix::MsgService::CommonMessages::NackDetails::InitAsDefaultInstance();
}

void InitDefaultsNackDetails() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsNackDetailsImpl);
}

void InitDefaultsLogonImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::Matrix::MsgService::CommonMessages::_Logon_default_instance_;
    new (ptr) ::Matrix::MsgService::CommonMessages::Logon();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Matrix::MsgService::CommonMessages::Logon::InitAsDefaultInstance();
}

void InitDefaultsLogon() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsLogonImpl);
}

void InitDefaultsSubscribeImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::Matrix::MsgService::CommonMessages::_Subscribe_default_instance_;
    new (ptr) ::Matrix::MsgService::CommonMessages::Subscribe();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Matrix::MsgService::CommonMessages::Subscribe::InitAsDefaultInstance();
}

void InitDefaultsSubscribe() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSubscribeImpl);
}

}  // namespace protobuf_CommonMessages_2eproto
namespace Matrix {
namespace MsgService {
namespace CommonMessages {
bool MsgType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 100:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void Header::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Header::kMsgTypeIDFieldNumber;
const int Header::kMsgKeyFieldNumber;
const int Header::kOrigClientTypeFieldNumber;
const int Header::kOrigClientIDFieldNumber;
const int Header::kDestClientTypeFieldNumber;
const int Header::kDestClientIDFieldNumber;
const int Header::kAckKeysFieldNumber;
const int Header::kTopicFieldNumber;
const int Header::kIsArchivedFieldNumber;
const int Header::kReplyMsgKeyFieldNumber;
const int Header::kMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Header::Header()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_CommonMessages_2eproto::InitDefaultsHeader();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Matrix.MsgService.CommonMessages.Header)
}
Header::Header(const Header& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      ackkeys_(from.ackkeys_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.msg().size() > 0) {
    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
  ::memcpy(&msgtypeid_, &from.msgtypeid_,
    static_cast<size_t>(reinterpret_cast<char*>(&replymsgkey_) -
    reinterpret_cast<char*>(&msgtypeid_)) + sizeof(replymsgkey_));
  // @@protoc_insertion_point(copy_constructor:Matrix.MsgService.CommonMessages.Header)
}

void Header::SharedCtor() {
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&msgtypeid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&replymsgkey_) -
      reinterpret_cast<char*>(&msgtypeid_)) + sizeof(replymsgkey_));
  _cached_size_ = 0;
}

Header::~Header() {
  // @@protoc_insertion_point(destructor:Matrix.MsgService.CommonMessages.Header)
  SharedDtor();
}

void Header::SharedDtor() {
  msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Header::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Header& Header::default_instance() {
  ::protobuf_CommonMessages_2eproto::InitDefaultsHeader();
  return *internal_default_instance();
}

Header* Header::New(::google::protobuf::Arena* arena) const {
  Header* n = new Header;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Header::Clear() {
// @@protoc_insertion_point(message_clear_start:Matrix.MsgService.CommonMessages.Header)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ackkeys_.Clear();
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&msgtypeid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&replymsgkey_) -
      reinterpret_cast<char*>(&msgtypeid_)) + sizeof(replymsgkey_));
  _internal_metadata_.Clear();
}

bool Header::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:Matrix.MsgService.CommonMessages.Header)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Matrix.MsgService.CommonMessages.MsgType msgTypeID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_msgtypeid(static_cast< ::Matrix::MsgService::CommonMessages::MsgType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 msgKey = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &msgkey_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 origClientType = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &origclienttype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 origClientID = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &origclientid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 destClientType = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &destclienttype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 destClientID = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &destclientid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 ackKeys = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_ackkeys())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 58u, input, this->mutable_ackkeys())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 topic = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &topic_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool isArchived = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isarchived_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 replyMsgKey = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &replymsgkey_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes msg = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(122u /* 122 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_msg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Matrix.MsgService.CommonMessages.Header)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Matrix.MsgService.CommonMessages.Header)
  return false;
#undef DO_
}

void Header::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Matrix.MsgService.CommonMessages.Header)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Matrix.MsgService.CommonMessages.MsgType msgTypeID = 1;
  if (this->msgtypeid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msgtypeid(), output);
  }

  // int32 msgKey = 2;
  if (this->msgkey() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->msgkey(), output);
  }

  // int32 origClientType = 3;
  if (this->origclienttype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->origclienttype(), output);
  }

  // int32 origClientID = 4;
  if (this->origclientid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->origclientid(), output);
  }

  // int32 destClientType = 5;
  if (this->destclienttype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->destclienttype(), output);
  }

  // int32 destClientID = 6;
  if (this->destclientid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->destclientid(), output);
  }

  // repeated int32 ackKeys = 7;
  if (this->ackkeys_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(7, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _ackkeys_cached_byte_size_));
  }
  for (int i = 0, n = this->ackkeys_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->ackkeys(i), output);
  }

  // int32 topic = 8;
  if (this->topic() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->topic(), output);
  }

  // bool isArchived = 9;
  if (this->isarchived() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->isarchived(), output);
  }

  // int32 replyMsgKey = 10;
  if (this->replymsgkey() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(10, this->replymsgkey(), output);
  }

  // bytes msg = 15;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      15, this->msg(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:Matrix.MsgService.CommonMessages.Header)
}

size_t Header::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Matrix.MsgService.CommonMessages.Header)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated int32 ackKeys = 7;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->ackkeys_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _ackkeys_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // bytes msg = 15;
  if (this->msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->msg());
  }

  // .Matrix.MsgService.CommonMessages.MsgType msgTypeID = 1;
  if (this->msgtypeid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->msgtypeid());
  }

  // int32 msgKey = 2;
  if (this->msgkey() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->msgkey());
  }

  // int32 origClientType = 3;
  if (this->origclienttype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->origclienttype());
  }

  // int32 origClientID = 4;
  if (this->origclientid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->origclientid());
  }

  // int32 destClientType = 5;
  if (this->destclienttype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->destclienttype());
  }

  // int32 destClientID = 6;
  if (this->destclientid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->destclientid());
  }

  // int32 topic = 8;
  if (this->topic() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->topic());
  }

  // bool isArchived = 9;
  if (this->isarchived() != 0) {
    total_size += 1 + 1;
  }

  // int32 replyMsgKey = 10;
  if (this->replymsgkey() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->replymsgkey());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Header::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Header*>(&from));
}

void Header::MergeFrom(const Header& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Matrix.MsgService.CommonMessages.Header)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  ackkeys_.MergeFrom(from.ackkeys_);
  if (from.msg().size() > 0) {

    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
  if (from.msgtypeid() != 0) {
    set_msgtypeid(from.msgtypeid());
  }
  if (from.msgkey() != 0) {
    set_msgkey(from.msgkey());
  }
  if (from.origclienttype() != 0) {
    set_origclienttype(from.origclienttype());
  }
  if (from.origclientid() != 0) {
    set_origclientid(from.origclientid());
  }
  if (from.destclienttype() != 0) {
    set_destclienttype(from.destclienttype());
  }
  if (from.destclientid() != 0) {
    set_destclientid(from.destclientid());
  }
  if (from.topic() != 0) {
    set_topic(from.topic());
  }
  if (from.isarchived() != 0) {
    set_isarchived(from.isarchived());
  }
  if (from.replymsgkey() != 0) {
    set_replymsgkey(from.replymsgkey());
  }
}

void Header::CopyFrom(const Header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Matrix.MsgService.CommonMessages.Header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Header::IsInitialized() const {
  return true;
}

void Header::Swap(Header* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Header::InternalSwap(Header* other) {
  using std::swap;
  ackkeys_.InternalSwap(&other->ackkeys_);
  msg_.Swap(&other->msg_);
  swap(msgtypeid_, other->msgtypeid_);
  swap(msgkey_, other->msgkey_);
  swap(origclienttype_, other->origclienttype_);
  swap(origclientid_, other->origclientid_);
  swap(destclienttype_, other->destclienttype_);
  swap(destclientid_, other->destclientid_);
  swap(topic_, other->topic_);
  swap(isarchived_, other->isarchived_);
  swap(replymsgkey_, other->replymsgkey_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string Header::GetTypeName() const {
  return "Matrix.MsgService.CommonMessages.Header";
}


// ===================================================================

void NackDetails::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NackDetails::kReasonFieldNumber;
const int NackDetails::kDetailsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NackDetails::NackDetails()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_CommonMessages_2eproto::InitDefaultsNackDetails();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Matrix.MsgService.CommonMessages.NackDetails)
}
NackDetails::NackDetails(const NackDetails& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  details_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.details().size() > 0) {
    details_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.details_);
  }
  reason_ = from.reason_;
  // @@protoc_insertion_point(copy_constructor:Matrix.MsgService.CommonMessages.NackDetails)
}

void NackDetails::SharedCtor() {
  details_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reason_ = 0;
  _cached_size_ = 0;
}

NackDetails::~NackDetails() {
  // @@protoc_insertion_point(destructor:Matrix.MsgService.CommonMessages.NackDetails)
  SharedDtor();
}

void NackDetails::SharedDtor() {
  details_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void NackDetails::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const NackDetails& NackDetails::default_instance() {
  ::protobuf_CommonMessages_2eproto::InitDefaultsNackDetails();
  return *internal_default_instance();
}

NackDetails* NackDetails::New(::google::protobuf::Arena* arena) const {
  NackDetails* n = new NackDetails;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NackDetails::Clear() {
// @@protoc_insertion_point(message_clear_start:Matrix.MsgService.CommonMessages.NackDetails)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  details_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reason_ = 0;
  _internal_metadata_.Clear();
}

bool NackDetails::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:Matrix.MsgService.CommonMessages.NackDetails)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 reason = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &reason_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string details = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_details()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->details().data(), static_cast<int>(this->details().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Matrix.MsgService.CommonMessages.NackDetails.details"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Matrix.MsgService.CommonMessages.NackDetails)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Matrix.MsgService.CommonMessages.NackDetails)
  return false;
#undef DO_
}

void NackDetails::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Matrix.MsgService.CommonMessages.NackDetails)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 reason = 1;
  if (this->reason() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->reason(), output);
  }

  // string details = 2;
  if (this->details().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->details().data(), static_cast<int>(this->details().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Matrix.MsgService.CommonMessages.NackDetails.details");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->details(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:Matrix.MsgService.CommonMessages.NackDetails)
}

size_t NackDetails::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Matrix.MsgService.CommonMessages.NackDetails)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string details = 2;
  if (this->details().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->details());
  }

  // int32 reason = 1;
  if (this->reason() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->reason());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NackDetails::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const NackDetails*>(&from));
}

void NackDetails::MergeFrom(const NackDetails& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Matrix.MsgService.CommonMessages.NackDetails)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.details().size() > 0) {

    details_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.details_);
  }
  if (from.reason() != 0) {
    set_reason(from.reason());
  }
}

void NackDetails::CopyFrom(const NackDetails& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Matrix.MsgService.CommonMessages.NackDetails)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NackDetails::IsInitialized() const {
  return true;
}

void NackDetails::Swap(NackDetails* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NackDetails::InternalSwap(NackDetails* other) {
  using std::swap;
  details_.Swap(&other->details_);
  swap(reason_, other->reason_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string NackDetails::GetTypeName() const {
  return "Matrix.MsgService.CommonMessages.NackDetails";
}


// ===================================================================

void Logon::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Logon::kClientTypeFieldNumber;
const int Logon::kClientIDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Logon::Logon()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_CommonMessages_2eproto::InitDefaultsLogon();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Matrix.MsgService.CommonMessages.Logon)
}
Logon::Logon(const Logon& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&clienttype_, &from.clienttype_,
    static_cast<size_t>(reinterpret_cast<char*>(&clientid_) -
    reinterpret_cast<char*>(&clienttype_)) + sizeof(clientid_));
  // @@protoc_insertion_point(copy_constructor:Matrix.MsgService.CommonMessages.Logon)
}

void Logon::SharedCtor() {
  ::memset(&clienttype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&clientid_) -
      reinterpret_cast<char*>(&clienttype_)) + sizeof(clientid_));
  _cached_size_ = 0;
}

Logon::~Logon() {
  // @@protoc_insertion_point(destructor:Matrix.MsgService.CommonMessages.Logon)
  SharedDtor();
}

void Logon::SharedDtor() {
}

void Logon::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Logon& Logon::default_instance() {
  ::protobuf_CommonMessages_2eproto::InitDefaultsLogon();
  return *internal_default_instance();
}

Logon* Logon::New(::google::protobuf::Arena* arena) const {
  Logon* n = new Logon;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Logon::Clear() {
// @@protoc_insertion_point(message_clear_start:Matrix.MsgService.CommonMessages.Logon)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&clienttype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&clientid_) -
      reinterpret_cast<char*>(&clienttype_)) + sizeof(clientid_));
  _internal_metadata_.Clear();
}

bool Logon::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:Matrix.MsgService.CommonMessages.Logon)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 clientType = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &clienttype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 clientID = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &clientid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Matrix.MsgService.CommonMessages.Logon)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Matrix.MsgService.CommonMessages.Logon)
  return false;
#undef DO_
}

void Logon::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Matrix.MsgService.CommonMessages.Logon)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 clientType = 1;
  if (this->clienttype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->clienttype(), output);
  }

  // int32 clientID = 2;
  if (this->clientid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->clientid(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:Matrix.MsgService.CommonMessages.Logon)
}

size_t Logon::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Matrix.MsgService.CommonMessages.Logon)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int32 clientType = 1;
  if (this->clienttype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->clienttype());
  }

  // int32 clientID = 2;
  if (this->clientid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->clientid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Logon::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Logon*>(&from));
}

void Logon::MergeFrom(const Logon& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Matrix.MsgService.CommonMessages.Logon)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.clienttype() != 0) {
    set_clienttype(from.clienttype());
  }
  if (from.clientid() != 0) {
    set_clientid(from.clientid());
  }
}

void Logon::CopyFrom(const Logon& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Matrix.MsgService.CommonMessages.Logon)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Logon::IsInitialized() const {
  return true;
}

void Logon::Swap(Logon* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Logon::InternalSwap(Logon* other) {
  using std::swap;
  swap(clienttype_, other->clienttype_);
  swap(clientid_, other->clientid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string Logon::GetTypeName() const {
  return "Matrix.MsgService.CommonMessages.Logon";
}


// ===================================================================

void Subscribe::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Subscribe::kClientTypeFieldNumber;
const int Subscribe::kClientIDFieldNumber;
const int Subscribe::kTopicFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Subscribe::Subscribe()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_CommonMessages_2eproto::InitDefaultsSubscribe();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Matrix.MsgService.CommonMessages.Subscribe)
}
Subscribe::Subscribe(const Subscribe& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&clienttype_, &from.clienttype_,
    static_cast<size_t>(reinterpret_cast<char*>(&topic_) -
    reinterpret_cast<char*>(&clienttype_)) + sizeof(topic_));
  // @@protoc_insertion_point(copy_constructor:Matrix.MsgService.CommonMessages.Subscribe)
}

void Subscribe::SharedCtor() {
  ::memset(&clienttype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&topic_) -
      reinterpret_cast<char*>(&clienttype_)) + sizeof(topic_));
  _cached_size_ = 0;
}

Subscribe::~Subscribe() {
  // @@protoc_insertion_point(destructor:Matrix.MsgService.CommonMessages.Subscribe)
  SharedDtor();
}

void Subscribe::SharedDtor() {
}

void Subscribe::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Subscribe& Subscribe::default_instance() {
  ::protobuf_CommonMessages_2eproto::InitDefaultsSubscribe();
  return *internal_default_instance();
}

Subscribe* Subscribe::New(::google::protobuf::Arena* arena) const {
  Subscribe* n = new Subscribe;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Subscribe::Clear() {
// @@protoc_insertion_point(message_clear_start:Matrix.MsgService.CommonMessages.Subscribe)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&clienttype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&topic_) -
      reinterpret_cast<char*>(&clienttype_)) + sizeof(topic_));
  _internal_metadata_.Clear();
}

bool Subscribe::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:Matrix.MsgService.CommonMessages.Subscribe)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 clientType = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &clienttype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 clientID = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &clientid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 topic = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &topic_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Matrix.MsgService.CommonMessages.Subscribe)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Matrix.MsgService.CommonMessages.Subscribe)
  return false;
#undef DO_
}

void Subscribe::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Matrix.MsgService.CommonMessages.Subscribe)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 clientType = 1;
  if (this->clienttype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->clienttype(), output);
  }

  // int32 clientID = 2;
  if (this->clientid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->clientid(), output);
  }

  // int32 topic = 3;
  if (this->topic() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->topic(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:Matrix.MsgService.CommonMessages.Subscribe)
}

size_t Subscribe::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Matrix.MsgService.CommonMessages.Subscribe)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int32 clientType = 1;
  if (this->clienttype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->clienttype());
  }

  // int32 clientID = 2;
  if (this->clientid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->clientid());
  }

  // int32 topic = 3;
  if (this->topic() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->topic());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Subscribe::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Subscribe*>(&from));
}

void Subscribe::MergeFrom(const Subscribe& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Matrix.MsgService.CommonMessages.Subscribe)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.clienttype() != 0) {
    set_clienttype(from.clienttype());
  }
  if (from.clientid() != 0) {
    set_clientid(from.clientid());
  }
  if (from.topic() != 0) {
    set_topic(from.topic());
  }
}

void Subscribe::CopyFrom(const Subscribe& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Matrix.MsgService.CommonMessages.Subscribe)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Subscribe::IsInitialized() const {
  return true;
}

void Subscribe::Swap(Subscribe* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Subscribe::InternalSwap(Subscribe* other) {
  using std::swap;
  swap(clienttype_, other->clienttype_);
  swap(clientid_, other->clientid_);
  swap(topic_, other->topic_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string Subscribe::GetTypeName() const {
  return "Matrix.MsgService.CommonMessages.Subscribe";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace CommonMessages
}  // namespace MsgService
}  // namespace Matrix

// @@protoc_insertion_point(global_scope)
#ifdef _WIN32
#pragma warning( pop )
#endif
