#!/bin/sh
# This shellscript sets the cross compiling environment back to the local VM

# Reset all the stuff that may have been set for another cross compiler.
export CRITICALLINK_HOME=""
export CRITICALLINK_TRIPLET=""
export CRITICALLINK_SYSROOTS=""
export SDKTARGETSYSROOT="/"
export PKG_CONFIG_SYSROOT_DIR=""
export PKG_CONFIG_PATH=""
export CONFIG_SITE=""
export OECORE_NATIVE_SYSROOT=""
export OECORE_TARGET_SYSROOT=""
export OECORE_ACLOCAL_OPTS=""
export TARGET_PREFIX=""
export CC=""
export CXX=""
export CPP=""
export AS=""
export LD=""
export GDB=""
export STRIP=""
export RANLIB=""
export OBJCOPY=""
export OBJDUMP=""
export AR=""
export NM=""
export M4=""
export CONFIGURE_FLAGS=""
export CFLAGS=""
export CXXFLAGS=""
export LDFLAGS=""
export CPPFLAGS=""
export OECORE_DISTRO_VERSION=""
export OECORE_SDK_VERSION=""
export ARCH=""

export CROSS_COMPILE_FULL_HOST="/"
export CROSS_COMPILE_HOST="${CROSS_COMPILE_BUILD}"
export CROSS_COMPILE=""
export CROSS_COMPILE_FULL=""
export CROSS_COMPILER_HOME="/usr/bin"
export COMPILE_TYPE=""

